# Generated by Django 2.0.5 on 2018-06-14 09:47

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180510_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attach',
            field=models.FileField(blank=True, upload_to=todo.models.todo_attach_path, verbose_name='副健'),
        ),
    ]
